apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-test-deploy
  namespace: default
  labels:
    numPods: "4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: as-test-app
  template:
    metadata:
      labels:
        app: as-test-app
    spec:
      containers:
      - name: as-test-pod
        image: lyudmilalala/as-test-img:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "50Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: as-test-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 30050
  selector:
    app: as-test-app