apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-monitor-pv1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 3Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: monitor-v1
    volumeAttributes:
      collection: monitor
      replication: "000"
      path: /monitor
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  storageClassName: ""
  volumeName: seaweedfs-monitor-pv1
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
