kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: seaweedfs-monitor-sc
provisioner: seaweedfs-csi-driver
parameters:
  collection: monitor
  replication: "000"
---            
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-monitor-pv1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 3Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: dfs-test
    volumeAttributes:
      collection: monitor
      replication: "000"
      path: /monitor
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: seaweedfs-monitor-sc
  volumeMode: Filesystem   
---            
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-monitor-pv2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 3Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: dfs-test
    volumeAttributes:
      collection: monitor
      replication: "000"
      path: /monitor
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: seaweedfs-monitor-sc
  volumeMode: Filesystem   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  storageClassName: seaweedfs-monitor-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: seaweedfs-monitor-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
