apiVersion: v1
kind: Namespace
metadata:
  name: appb-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appb-deploy
  namespace: appb-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appb-app
  template:
    metadata:
      labels:
        app: appb-app
    spec:
      containers:
      - name: appb-pod
        image: crpi-foj3lu39cfzgj05z.cn-shenzhen.personal.cr.aliyuncs.com/jerry-learn/app-b:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appb-svc
  namespace: appb-ns
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30062
  selector:
    app: appb-app