apiVersion: v1
kind: Namespace
metadata:
  name: busybox-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deploy
  namespace: busybox-ns
  labels:
    app: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
      - name: busybox
        image: ubuntu:22.04
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c", "while true; do echo 'hello in loop'; sleep 10;done"]