---
# Source: my-first-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chart-demo-my-first-chart
  labels:
    helm.sh/chart: my-first-chart-0.0.1
    app.kubernetes.io/name: my-first-chart
    app.kubernetes.io/instance: chart-demo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: my-first-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chart-demo-my-first-chart
  labels:
    helm.sh/chart: my-first-chart-0.0.1
    app.kubernetes.io/name: my-first-chart
    app.kubernetes.io/instance: chart-demo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30050
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: my-first-chart
    app.kubernetes.io/instance: chart-demo
---
# Source: my-first-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-demo-my-first-chart
  labels:
    helm.sh/chart: my-first-chart-0.0.1
    app.kubernetes.io/name: my-first-chart
    app.kubernetes.io/instance: chart-demo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: my-first-chart
      app.kubernetes.io/instance: chart-demo
  template:
    metadata:
      labels:
        helm.sh/chart: my-first-chart-0.0.1
        app.kubernetes.io/name: my-first-chart
        app.kubernetes.io/instance: chart-demo
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
        app: flask-app
    spec:
      serviceAccountName: chart-demo-my-first-chart
      securityContext:
        {}
      containers:
        - name: my-first-chart
          securityContext:
            {}
          image: "crpi-foj3lu39cfzgj05z.cn-shenzhen.personal.cr.aliyuncs.com/jerry-learn/flask-test:2.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livenessCheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readinessCheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
          - name: APP_NAME
            value: Jerry-learning
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            {}
---
# Source: my-first-chart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "chart-demo-my-first-chart-test-connection"
  labels:
    helm.sh/chart: my-first-chart-0.0.1
    app.kubernetes.io/name: my-first-chart
    app.kubernetes.io/instance: chart-demo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['chart-demo-my-first-chart:8080']
  restartPolicy: Never
