server:
  service:
    type: NodePort
    nodePort: 30103
    port: 9090
  persistentVolume:
      enabled: false
      storageClass: "prometheus-sc"
      # existingClaim: "prometheus-pvc"
      # subPath: /prometheus
      size: 10Gi
  retention: "2d"
alertmanager:
  enabled: false
extraScrapeConfigs: |
  - job_name: 'mysql-master'
    static_configs:
      - targets: ['192.168.1.248:9104']
        labels:
          instance: mysql-master
          role: master
  - job_name: 'mysql-slave'
    static_configs:
      - targets: ['192.168.1.249:9104']
        labels:
          instance: mysql-slave
          role: slave
  - job_name: 'external-nodes'
      static_configs:
        - targets:
            - '192.168.1.250:9100'
          labels:
            cluster: 'external'  
      relabel_configs:
        - source_labels: [__address__]
          regex: '([^:]+):\d+'
          target_label: 'instance'
          replacement: '$1'
          action: replace