server:
  service:
    type: NodePort
    nodePort: 30103
    port: 9090
  persistentVolume:
      enabled: false
      storageClass: "prometheus-sc"
      # existingClaim: "prometheus-pvc"
      # subPath: /prometheus
      size: 10Gi
  retention: "2d"
alertmanager:
  enabled: false
prometheus-node-exporter:
  enabled: false
