loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        # object_store: s3
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    filesystem:
      directory: /tmp/loki/chunks
  # storage_config:
  # aws:
      # s3: http://123:456@192.168.1.250:8333
      #  s3forcepathstyle: false
      # bucketnames: loki-chunk
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  querier:
    max_concurrent: 4
  storage:
    type: filesystem
    # type: s3
    # s3:
    #   s3: http://123:456@192.168.1.250:8333
    #   s3ForcePathStyle: false
    #   insecure: true
    bucketNames:
        chunks: loki-chunk
        ruler: loki-ruler
        admin: loki-admin

minio:
  enabled: false

gateway:
  service:
    type: NodePort
    port: 80
    nodePort: 30102

deploymentMode: SingleBinary

chunksCache:
  allocatedMemory: 1024

singleBinary:
  replicas: 1
  persistence:
    enabled: false
    storageClass: loki-sc
    size: 10Gi

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
