apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-func-deploy
  namespace: go-func
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-func-app
  template:
    metadata:
      labels:
        app: go-func-app
    spec:
      containers:
      - name: go-func-pod
        image: lyudmilalala/go_http_server:1.2.0
        env:
        - name: APP_PORT
          value: "5080"
        - name: APP_LOG_LEVEL
          value: "INFO"
        - name: VERSION
          value: "1.2.0"
        - name: APP_LIVENESS_TEST
          value: "N"
        resources:
          requests:
            cpu: "100m"
            memory: "10Mi"
          limits:
            cpu: "100m"
            memory: "10Mi"
        ports:
        - containerPort: 5080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: go-func-svc
  namespace: go-func
spec:
  type: NodePort
  ports:
  - port: 5080
    protocol: TCP
    nodePort: 30090
  selector:
    app: go-func-app