apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: busybox-updater
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "patch", "update", "delete", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "patch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: busybox-auth-binding
subjects:
- kind: ServiceAccount
  name: busybox-admin
  namespace:  busybox-ns
roleRef:
  kind: ClusterRole
  name: busybox-updater
  apiGroup: rbac.authorization.k8s.io