apiVersion: v1
kind: ServiceAccount
metadata:
  name: busybox-admin
  namespace: busybox-ns 

---
  
apiVersion: v1
kind: Secret
metadata:
  name: busybox-access-secret
  namespace: busybox-ns 
  annotations:
    kubernetes.io/service-account.name: busybox-admin
type: kubernetes.io/service-account-token

