apiVersion: v1
kind: Namespace
metadata:
  name: flask-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  namespace: flask-ns
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-pod
    image: crpi-foj3lu39cfzgj05z.cn-shenzhen.personal.cr.aliyuncs.com/jerry-learn/flask-test:3.0.0
    imagePullPolicy: IfNotPresent
    ports:
    - name: liveness-port
      containerPort: 8080
    resources:
      requests:
        cpu: "100m"
        memory: "10Mi"
      limits:
        cpu: "1000m"
        memory: "100Mi"
    readinessProbe:
      httpGet:
        path: /readinessCheck
        port: liveness-port
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /livenessCheck
        port: liveness-port
      initialDelaySeconds: 5
      periodSeconds: 2
      failureThreshold: 3
    startupProbe:
      httpGet:
        path: /startCheck
        port: liveness-port
      failureThreshold: 10
      periodSeconds: 5
    env:
    - name: APP_NAME
      value: "Jerry-learning"
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: flask-ns
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30050
  selector:
    app: flask-app
