apiVersion: v1
kind: Pod
metadata:
  name: flask-pod-2
  namespace: flask-ns
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-pod-2
    image: crpi-foj3lu39cfzgj05z.cn-shenzhen.personal.cr.aliyuncs.com/jerry-learn/flask-test:3.0.0
    imagePullPolicy: IfNotPresent
    ports:
    - name: liveness-port
      containerPort: 8080
    resources:
      requests:
        cpu: "100m"
        memory: "10Mi"
      limits:
        cpu: "1000m"
        memory: "100Mi"
    env:
    - name: APP_NAME
      value: "Jerry-learning"
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
~                                     
